# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        KarfilmsBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: KarfilmsBundle:Usuario
                property: nombre

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /iniciar-sesion
                check_path: /iniciar-sesion_check
            logout:
                path: /logout
                target: /iniciar-sesion
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
