KarfilmsBundle\Entity\Actor:
    type: entity
    table: actores
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    oneToMany:
        Actorpelicula:
            targetEntity: Actorpelicula
            mappedBy: idActor
            cascade: ["persist"]
    lifecycleCallbacks: {  }
