KarfilmsBundle\Entity\Actorpelicula:
    type: entity
    table: actorespeliculas
    indexes:
        fk_id_actor_idx:
            columns:
                - id_actor
        fk_id_pelicula_idx:
            columns:
                - id_pelicula               
    uniqueConstraints:
        fk_actorpeli_idx:
          columns:
              - id_actor
              - id_pelicula
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idPelicula:
            targetEntity: Pelicula
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: Actorpelicula
            joinColumns:
                id_pelicula:
                    referencedColumnName: id
            orphanRemoval: false
        idActor:
            targetEntity: Actor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_actor:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
