KarfilmsBundle\Entity\Asiento:
    type: entity
    table: asientos
    indexes:
        fk_sala_idx:
            columns:
                - id_sala
    uniqueConstraints:
        fk_asientosala_idx:
          columns: [ fila, butaca, id_sala ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fila:
            type: integer
            nullable: false
            options:
                unsigned: true
        butaca:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        idSala:
            targetEntity: Sala
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: asiento
            joinColumns:
                id_sala:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        Asientoreservado:
            targetEntity: Asientoreservado
            mappedBy: idAsiento
            cascade: ["persist"]
    lifecycleCallbacks: {  }
