KarfilmsBundle\Entity\Asientoreservado:
    type: entity
    table: asientosreservados
    indexes:
        fk_seat_idx:
            columns:
                - id_asiento
        fk_session_idx:
            columns:
                - id_sesion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idAsiento:
            targetEntity: Asiento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_asiento:
                    referencedColumnName: id
            orphanRemoval: false
        idSesion:
            targetEntity: Sesion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sesion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
