KarfilmsBundle\Entity\Entrada:
    type: entity
    table: entradas
    indexes:
        fk_id_sesion_idx:
            columns:
                - id_sesion
        fk_id_user_idx:
            columns:
                - id_usuario
        fk_asiento_idx:
            columns:
                - id_asiento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idSesion:
            targetEntity: Sesion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sesion:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
        idAsiento:
            targetEntity: Asiento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_asiento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
