KarfilmsBundle\Entity\Genero:
    type: entity
    table: generos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    oneToMany:
        Generopelicula:
            targetEntity: Generopelicula
            mappedBy: idGenero
            cascade: ["persist"]
    lifecycleCallbacks: {  }
