KarfilmsBundle\Entity\Pelicula:
    type: entity
    table: peliculas
    indexes:
        fk_edad_idx:
            columns:
                - id_edad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        sinopsis:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        cartel:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        trailer:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        duracion:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idEdad:
            targetEntity: Edad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: pelicula
            joinColumns:
                id_edad:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        Generopelicula:
            targetEntity: Generopelicula
            mappedBy: idPelicula
            cascade: ["persist"]
        Actorpelicula:
            targetEntity: Actorpelicula
            mappedBy: idPelicula
            cascade: ["persist"]
        Directorpelicula:
            targetEntity: Directorpelicula
            mappedBy: idPelicula
            cascade: ["persist"]
        sesion:
            targetEntity: Sesion
            mappedBy: idPelicula
            cascade: ["persist"]
    lifecycleCallbacks: {  }