KarfilmsBundle\Entity\Sesion:
    type: entity
    table: sesiones
    indexes:
        fk_id_sala_idx:
            columns:
                - id_sala
        fk_id_pelicula_idx:
            columns:
                - id_pelicula
    uniqueConstraints:
        fk_horarios:
            columns:
                - id_sala
                - horarios
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        horarios:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        idPelicula:
            targetEntity: Pelicula
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: sesion
            joinColumns:
                id_pelicula:
                    referencedColumnName: id
            orphanRemoval: false
        idSala:
            targetEntity: Sala
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_sala:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        Asientoreservado:
            targetEntity: Asientoreservado
            mappedBy: idSesion
            cascade: ["persist"]
    lifecycleCallbacks: {  }
