KarfilmsBundle\Entity\Sugerencia:
    type: entity
    table: sugerencias
    indexes:
        fk_id_usuario_idx:
            columns:
                - id_usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
