registrarse:
    path: /registrarse
    defaults: { _controller: KarfilmsBundle:Usuario:registrarse }

iniciar_sesion:
    path: /iniciar-sesion
    defaults: { _controller: KarfilmsBundle:Usuario:iniciarSesion }
    
iniciar_sesion_check:
    path: /iniciar-sesion_check
    
logout:
    path: /logout
        
inicio:
    path: /inicio
    defaults: { _controller: KarfilmsBundle:Default:index }
    
indice_genero:
    path: /admin/generos
    defaults: { _controller: KarfilmsBundle:Genero:indiceGenero }
    
add_genero:
    path: /admin/generos/nuevo-genero
    defaults: { _controller: KarfilmsBundle:Genero:addGenero }