###################REGISTRO DE USUARIOS E INICIO DE SESIÓN###################
registrarse:
    path: /registrarse
    defaults: { _controller: KarfilmsBundle:Usuario:registrarse }

iniciar_sesion:
    path: /iniciar-sesion
    defaults: { _controller: KarfilmsBundle:Usuario:iniciarSesion }
    
iniciar_sesion_check:
    path: /iniciar-sesion_check
    
logout:
    path: /logout

###################ACCIONES SOBRE LOS USUARIOS###################
mi_perfil:
    path: /mi-perfil/{id}
    defaults: { _controller: KarfilmsBundle:Usuario:miPerfil }
    
perfil_usuario:
    path: /{nombre}-{id}
    defaults: { _controller: KarfilmsBundle:Usuario:perfilUsuario }
    
indice_usuario:
    path: /admin/usuarios
    defaults: { _controller: KarfilmsBundle:Usuario:indiceUsuario }
    
editar_usuario:
    path: /mi-perfil/editar/{id}
    defaults: { _controller: KarfilmsBundle:Usuario:editarUsuario }

cambiar_icono:
    path: /mi-perfil/cambiar-icono/{id}
    defaults: { _controller: KarfilmsBundle:Usuario:cambiarIcono }
    
eliminar_usuario:
    path: /admin/usuarios/eliminar-usuario/{id}
    defaults: { _controller: KarfilmsBundle:Usuario:eliminarUsuario }
    
hacer_administrador:
    path: /admin/administrador/{id}
    defaults: {_controller: KarfilmsBundle:Usuario:administrador}

###################ACCIONES SOBRE LOS GÉNEROS###################
indice_genero:
    path: /admin/generos
    defaults: { _controller: KarfilmsBundle:Genero:indiceGenero }
    
add_genero:
    path: /admin/generos/nuevo-genero
    defaults: { _controller: KarfilmsBundle:Genero:addGenero }
    
eliminar_genero:
    path: /admin/generos/eliminar-genero/{id}
    defaults: { _controller: KarfilmsBundle:Genero:eliminarGenero }

editar_genero:
    path: /admin/generos/editar-genero/{id}
    defaults: { _controller: KarfilmsBundle:Genero:editarGenero }

###################ACCIONES SOBRE LOS ACTORES###################
indice_actor:
    path: /admin/actores
    defaults: { _controller: KarfilmsBundle:Actor:indiceActor }
    
add_actor:
    path: /admin/actores/nuevo-actor
    defaults: { _controller: KarfilmsBundle:Actor:addActor }

eliminar_actor:
    path: /admin/actores/eliminar-actor/{id}
    defaults: { _controller: KarfilmsBundle:Actor:eliminarActor }
    
editar_actor:
    path: /admin/actores/editar-actor/{id}
    defaults: { _controller: KarfilmsBundle:Actor:editarActor }

###################ACCIONES SOBRE LAS CLASIFICACIONES POR EDADES###################
indice_edad:
    path: /admin/edades
    defaults: { _controller: KarfilmsBundle:Edad:indiceEdad }
    
add_edad:
    path: /admin/edades/nueva-edad
    defaults: { _controller: KarfilmsBundle:Edad:addEdad }

eliminar_edad:
    path: /admin/edades/eliminar-edad/{id}
    defaults: { _controller: KarfilmsBundle:Edad:eliminarEdad }
    
editar_edad:
    path: /admin/edades/editar-edad/{id}
    defaults: { _controller: KarfilmsBundle:Edad:editarEdad }

###################ACCIONES SOBRE LAS SALAS###################
indice_sala:
    path: /admin/salas
    defaults: { _controller: KarfilmsBundle:Sala:indiceSala }
    
add_sala:
    path: /admin/salas/nueva-sala
    defaults: { _controller: KarfilmsBundle:Sala:addSala }

eliminar_sala:
    path: /admin/salas/eliminar-sala/{id}
    defaults: { _controller: KarfilmsBundle:Sala:eliminarSala}
    
editar_sala:
    path: /admin/salas/editar-sala/{id}
    defaults: { _controller: KarfilmsBundle:Sala:editarSala }

###################ACCIONES SOBRE LOS DIRECTORES###################
indice_director:
    path: /admin/directores
    defaults: { _controller: KarfilmsBundle:Director:indiceDirector }
    
add_director:
    path: /admin/directores/nuevo-director
    defaults: { _controller: KarfilmsBundle:Director:addDirector }

eliminar_director:
    path: /admin/directores/eliminar-director/{id}
    defaults: { _controller: KarfilmsBundle:Director:eliminarDirector }
    
editar_director:
    path: /admin/directores/editar-director/{id}
    defaults: { _controller: KarfilmsBundle:Director:editarDirector }

###################ACCIONES SOBRE LAS SESIONES###################
indice_sesion:
    path: /admin/sesiones
    defaults: { _controller: KarfilmsBundle:Sesion:indiceSesion }
    
add_sesion:
    path: /admin/sesiones/nueva-sesion
    defaults: { _controller: KarfilmsBundle:Sesion:addSesion }

eliminar_sesion:
    path: /admin/sesiones/eliminar-sesion/{id}
    defaults: { _controller: KarfilmsBundle:Sesion:eliminarSesion }
    
editar_sesion:
    path: /admin/sesiones/editar-sesion/{id}
    defaults: { _controller: KarfilmsBundle:Sesion:editarSesion }

###################ACCIONES SOBRE LAS PELÍCULAS###################
indice_pelicula:
    path: /admin/peliculas
    defaults: { _controller: KarfilmsBundle:Pelicula:indicePelicula }
    
add_pelicula:
    path: /admin/peliculas/nueva-pelicula
    defaults: { _controller: KarfilmsBundle:Pelicula:addPelicula }
    
mostrar_pelicula:
    path: /cartelera/{titulo}/{id}
    defaults: { _controller: KarfilmsBundle:Pelicula:mostrarPelicula }

detalles_pelicula:
    path: /admin/peliculas/detalles-pelicula/{id}
    defaults: { _controller: KarfilmsBundle:Pelicula:detallesPelicula }

eliminar_pelicula:
    path: /admin/peliculas/eliminar-pelicula/{id}
    defaults: { _controller: KarfilmsBundle:Pelicula:eliminarPelicula }
    
editar_pelicula:
    path: /admin/peliculas/editar-pelicula/{id}
    defaults: { _controller: KarfilmsBundle:Pelicula:editarPelicula }

###################ACCIONES SOBRE LOS ASIENTOS###################
indice_asiento:
    path: /admin/asientos
    defaults: { _controller: KarfilmsBundle:Asiento:indiceAsiento }

add_asiento:
    path: /admin/asientos/nuevo-asiento
    defaults: { _controller: KarfilmsBundle:Asiento:addAsiento }

eliminar_asiento:
    path: /admin/asientos/eliminar-asiento/{id}
    defaults: { _controller: KarfilmsBundle:Asiento:eliminarAsiento }
    
editar_asiento:
    path: /admin/asientos/editar-asiento/{id}
    defaults: { _controller: KarfilmsBundle:Asiento:editarAsiento }

###################ACCIONES SOBRE LA BARRA DE NAVEGACIÓN###################
#INICIO
inicio:
    path: /inicio
    defaults: { _controller: KarfilmsBundle:Default:index }
    
#CARTELERA
mostrar_cartelera:
    path: /cartelera
    defaults: { _controller: KarfilmsBundle:Pelicula:mostrarCartelera }
    
mostrar_sesiones_ajax:
    path: /mostrar_sesiones_ajax
    defaults: { _controller: KarfilmsBundle:Pelicula:sesionesPeliculaCarteleraAjax }
    
mostrar_peliculas_ajax:
    path: /mostrar_peliculas_ajax
    defaults: { _controller: KarfilmsBundle:Pelicula:peliculaAjax }

#SUGERENCIAS
mostrar_sugerencia:
    path: /sugerencias
    defaults: { _controller: KarfilmsBundle:Sugerencia:mostrarYaddSugerencia }
    
eliminar_sugerencia:
    path: /sugerencias/{id}
    defaults: { _controller: KarfilmsBundle:Sugerencia:eliminarSugerencia }

#GÉNEROS
mostrar_genero:
    path: /generos
    defaults: { _controller: KarfilmsBundle:Genero:mostrarGenero }
    
categoria_genero:
    path: /generos/{nombre}
    defaults: { _controller: KarfilmsBundle:Genero:categoriaGenero }
    
#ACTORES
mostrar_actor:
    path: /actores
    defaults: { _controller: KarfilmsBundle:Actor:mostrarActor }
    
categoria_actor:
    path: /actores/{nombre}
    defaults: { _controller: KarfilmsBundle:Actor:categoriaActor }
    
#DIRECTORES
mostrar_director:
    path: /directores
    defaults: { _controller: KarfilmsBundle:Director:mostrarDirector }
    
categoria_director:
    path: /directores/{nombre}
    defaults: { _controller: KarfilmsBundle:Director:categoriaDirector }