registrarse:
    path: /registrarse
    defaults: { _controller: KarfilmsBundle:Usuario:registrarse }

iniciar_sesion:
    path: /iniciar-sesion
    defaults: { _controller: KarfilmsBundle:Usuario:iniciarSesion }
    
iniciar_sesion_check:
    path: /iniciar-sesion_check
    
logout:
    path: /logout
        
inicio:
    path: /inicio
    defaults: { _controller: KarfilmsBundle:Default:index }