KarfilmsBundle\Entity\Genero:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío" }
            - Length:
                min: 2
                minMessage: "El nombre debe tener más de 2 caracteres"