KarfilmsBundle\Entity\Genero:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío." }
            - Length:
                min: 2
                minMessage: "El nombre debe tener mínimo 2 caracteres."

KarfilmsBundle\Entity\Sugerencia:
    properties:
        texto:
            - NotBlank: { message: "La sugerencia no puede estar vacía." }
            - Length:
                min: 1
                minMessage: "La sugerencia debe tener mínimo 1 caracter."
                
KarfilmsBundle\Entity\Actor:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío" }
            - Length:
                min: 1
                minMessage: "El nombre debe tener mínimo 1 caracter."
                
KarfilmsBundle\Entity\Director:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío" }
            - Length:
                min: 1
                minMessage: "El nombre debe tener mínimo 1 caracter."
                
KarfilmsBundle\Entity\Sala:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío" }
            - Length:
                min: 1
                max: 1
                minMessage: "El nombre sólo debe tener 1 caracter."
                
KarfilmsBundle\Entity\Usuario:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío" }
            - Length:
                min: 1
                minMessage: "El nombre debe tener mínimo 1 caracter."
        password:
            - Length:
                min: 8
                minMessage: "La contraseña debe tener mínimo 8 caracteres."

KarfilmsBundle\Entity\Edad:
    properties:
        clasificacion:
            - NotBlank: { message: "La clasificación no puede estar vacía." }
            - Length:
                min: 2
                minMessage: "La clasificación debe tener mínimo 2 caracteres. (Ej: +7)."